stages:
  - build
  - test

build:
  image: quay.io/centos/centos:stream9
  stage: build
  script:
    - dnf -y install 'dnf-command(config-manager)'
    - dnf -y config-manager --set-enabled crb
    - dnf -y install go-toolset libvirt-devel
    - make GOOPTS=-buildvcs=false
    - make test
