stages:
  - build
  - test

build:
  image: quay.io/centos/centos:stream9
  stage: build
  script:
    - dnf -y install 'dnf-command(config-manager)'
    - dnf -y config-manager --set-enabled crb
    - dnf -y install go-toolset libvirt-devel
    - go install github.com/onsi/ginkgo/v2/ginkgo@latest
    - make GOOPTS=-buildvcs=false
    - export PATH=$PATH:$HOME/go/bin
    - make test
