specfile_path: rpm/podman-bootc.spec
upstream_tag_template: v{version}

# add or remove files that should be synced
files_to_sync:
    - rpm/podman-bootc.spec
    - .packit.yaml

# name in upstream package repository or registry (e.g. in PyPI)
upstream_package_name: podman-bootc
# downstream (Fedora) RPM package name
downstream_package_name: podman-bootc

srpm_build_deps:
  - git-archive-all
  - make
  - golang

actions:
  fix-spec-file:
    - "bash rpm/packit.sh"

jobs:
  - job: copr_build
    trigger: pull_request
    enable_net: true
    targets:
      - fedora-all-x86_64

  - job: copr_build
    trigger: commit
    enable_net: true
    branch: main
    owner: gmaglione
    project: podman-bootc
    list_on_homepage: true
    preserve_project: true
    targets:
      - fedora-latest
      - fedora-rawhide

